[functions.crear-doctor]
enabled = true
verify_jwt = false
import_map = "./functions/crear-doctor/deno.json"
entrypoint = "./functions/crear-doctor/index.ts"

[functions.crear-usuario]
enabled = true
verify_jwt = false
import_map = "./functions/crear-usuario/deno.json"
entrypoint = "./functions/crear-usuario/index.ts"